# Learning Pandas

Pandas is a high-level data manipulation package which was built on top of Numpy. The key structures within pandas include Series and DataFrames

In [2]:
import numpy as np
import pandas as pd

## Series

A Series is a 1d ndarray with axis labels (an index)

In [3]:
# Creating a series from a list
x = pd.Series([10,20,30,40,50])
x

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
# Accessing the index
x.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
# Accessing the values
x.values

array([10, 20, 30, 40, 50])

In [6]:
# Accessing the data type of the Series
x.dtype

dtype('int64')

In [7]:
# Creating a Series with a custom index
data = [450, 650, 870]
Sales = pd.Series(data, index=["Don", "Mike", "Edwin"])
Sales

Don      450
Mike     650
Edwin    870
dtype: int64

In [8]:
# Check the type
type(Sales)

pandas.Series

In [9]:
Sales.index

Index(['Don', 'Mike', 'Edwin'], dtype='str')

## Accessing Values

In [10]:
# Using index names
Sales["Don"]

np.int64(450)

In [11]:
# We can still use positional index as well
Sales[0]

KeyError: 0

## Checking for conditions

In [12]:
# We can filter data based on conditions we specify.
Sales > 500

Don      False
Mike      True
Edwin     True
dtype: bool

In [13]:
Sales[[False, True, True]]

Mike     650
Edwin    870
dtype: int64

In [14]:
Sales[Sales>500]

Mike     650
Edwin    870
dtype: int64

In [15]:
# Checking the names in an index
"Don" in Sales

True

In [16]:
# This will return False as name is not in Series
"Sally" in Sales

False

In [18]:
450 in Sales # even though Don is 450, it comes back as false because you are only checking the index not the values

False

## Working with Dictionaries

In [19]:
# Converting a Series to a Python Dict
sales_dict = Sales.to_dict()
sales_dict

{'Don': 450, 'Mike': 650, 'Edwin': 870}

In [20]:
sales_ser = pd.Series(sales_dict)
sales_ser

Don      450
Mike     650
Edwin    870
dtype: int64

### Adding entries and working with NaN/null values (Not a Number)

In [21]:
# We can create a new Series from an already existing Series
new_sales = pd.Series(Sales, index=["Don", "Mike", "Sally", "Edwin", "Lucy"])
new_sales

Don      450.0
Mike     650.0
Sally      NaN
Edwin    870.0
Lucy       NaN
dtype: float64

In [22]:
# Check NaN values
print(np.isnan(new_sales["Sally"]))

True

In [23]:
# NaN is not the same as None
new_sales["Sally"] is None

False

In [24]:
# .isnan can be used on the entire Series
np.isnan(new_sales)

Don      False
Mike     False
Sally     True
Edwin    False
Lucy      True
dtype: bool

In [25]:
pd.isnull(new_sales)

Don      False
Mike     False
Sally     True
Edwin    False
Lucy      True
dtype: bool

### Naming components in a Series

In [26]:
# Naming an Index
Sales.index.name = "Sales Person"
Sales

Sales Person
Don      450
Mike     650
Edwin    870
dtype: int64

In [27]:
# Naming a Series
Sales.name = "Total TV Sales"
Sales

Sales Person
Don      450
Mike     650
Edwin    870
Name: Total TV Sales, dtype: int64

## DataFrames

DataFrames are two-dimensional (2d), size-mutable, potentially heterogeneous (diverse) tabular data structures. This data structure contains labeled axes (rows and columns).

In [29]:
### Creating a DataFrame (DF) from a list
df_data = [["Adrian", 20], ["Bethany", 23], ["Chloe", 41]]

# When creating the df, we need to give it the 2d array and the columns names we want it to use
df = pd.DataFrame(df_data, columns=["Name", "Age"])
df

      Name  Age
0   Adrian   20
1  Bethany   23
2    Chloe   41

In [30]:
# Creating a DataFrame from a dictionary
new_dict = {'Name':['Tom','Jane','Steve','Lucy'],'Sales':[250,300,350,400]}

df_dict = pd.DataFrame(new_dict)
df_dict

    Name  Sales
0    Tom    250
1   Jane    300
2  Steve    350
3   Lucy    400

In [32]:
# Adding a custom index
df_dict_index = pd.DataFrame(new_dict, index=["rank1", "rank2", "rank3", "rank4"])
df_dict_index

        Name  Sales
rank1    Tom    250
rank2   Jane    300
rank3  Steve    350
rank4   Lucy    400

In [33]:
# Creating a DataFrame from a list of Dictionaries
# This is the same data as we had previously, but in a different format
# This is useful when working with json
dict_list = [{'Name':'Tom','Sales':250},{'Name':'Jane','Sales':300},{'Name':'Steve','Sales':350},
             {'Name':'Lucy','Sales':400}]

df_dict_list = pd.DataFrame(dict_list)
df_dict_list

    Name  Sales
0    Tom    250
1   Jane    300
2  Steve    350
3   Lucy    400

In [35]:
# Creating a df from a dictionary of Series
east = pd.Series([1000, 1200, 3400], index=["Q1", "Q2", "Q3"])
east

Q1    1000
Q2    1200
Q3    3400
dtype: int64

In [36]:
west = pd.Series([1100, 1300, 2400, 3500], index=["Q1", "Q2", "Q3", "Q4"])
west

Q1    1100
Q2    1300
Q3    2400
Q4    3500
dtype: int64

In [37]:
# We can combine Series into a singlular df
df_region = pd.DataFrame({"East":east, "West":west})
df_region

      East  West
Q1  1000.0  1100
Q2  1200.0  1300
Q3  3400.0  2400
Q4     NaN  3500

In [38]:
# We can add more Series to the df, after it is created
df_region["North"] = [2000,3000,2500,4000]
df_region["South"] = [1500,2000,1500,4000]
df_region

      East  West  North  South
Q1  1000.0  1100   2000   1500
Q2  1200.0  1300   3000   2000
Q3  3400.0  2400   2500   1500
Q4     NaN  3500   4000   4000

In [39]:
years = ["2016", "2017", "2018", "2019"]
df_region["Years"] = years
df_region

      East  West  North  South Years
Q1  1000.0  1100   2000   1500  2016
Q2  1200.0  1300   3000   2000  2017
Q3  3400.0  2400   2500   1500  2018
Q4     NaN  3500   4000   4000  2019

In [40]:
# Make years the index rather than a column
df_region = df_region.set_index("Years")
df_region

         East  West  North  South
Years
2016   1000.0  1100   2000   1500
2017   1200.0  1300   3000   2000
2018   3400.0  2400   2500   1500
2019      NaN  3500   4000   4000

In [41]:
new_df = df_region.reindex(["2017", "2018", "2019", "2020", "2021"])
new_df

         East    West   North   South
Years
2017   1200.0  1300.0  3000.0  2000.0
2018   3400.0  2400.0  2500.0  1500.0
2019      NaN  3500.0  4000.0  4000.0
2020      NaN     NaN     NaN     NaN
2021      NaN     NaN     NaN     NaN

In [42]:
## reindex columns
re_indexed = new_df.reindex(columns=["North", "East", "South", "New"])
re_indexed

        North    East   South  New
Years
2017   3000.0  1200.0  2000.0  NaN
2018   2500.0  3400.0  1500.0  NaN
2019   4000.0     NaN  4000.0  NaN
2020      NaN     NaN     NaN  NaN
2021      NaN     NaN     NaN  NaN

### Missing Data

In [43]:
# Filling in missing values
# We may want to change all NaN values to 0 (or some specific number)
# This will be especially useful when working with certain types of algorithms
# Some algorithms cannot deal with NaN values
 
re_indexed.fillna(0) # note we are not actually assigning this to a new dataframe, this is temporary

        North    East   South  New
Years
2017   3000.0  1200.0  2000.0  0.0
2018   2500.0  3400.0  1500.0  0.0
2019   4000.0     0.0  4000.0  0.0
2020      0.0     0.0     0.0  0.0
2021      0.0     0.0     0.0  0.0

In [45]:
# If we don't want to fill with a single value, we can change the fill method
# methods we can pick from - ‘backfill’, ‘bfill’, ‘pad’, ‘ffill’
# These methods will take the last available value and carry it to the next item
re_indexed.ffill()

        North    East   South  New
Years
2017   3000.0  1200.0  2000.0  NaN
2018   2500.0  3400.0  1500.0  NaN
2019   4000.0  3400.0  4000.0  NaN
2020   4000.0  3400.0  4000.0  NaN
2021   4000.0  3400.0  4000.0  NaN

In [46]:
# Default method for interpolation is linear, this can be changed.
re_indexed.interpolate()

        North    East   South  New
Years
2017   3000.0  1200.0  2000.0  NaN
2018   2500.0  3400.0  1500.0  NaN
2019   4000.0  3400.0  4000.0  NaN
2020   4000.0  3400.0  4000.0  NaN
2021   4000.0  3400.0  4000.0  NaN

### Dropping items in Dataframes

In [47]:
# Sometimes we would rather drop than fill
re_indexed.dropna()

Empty DataFrame
Columns: [North, East, South, New]
Index: []

In [50]:
# We can specify columns and methods when dropping with .dropna()
# axis 1 = columns, 0 = rows
# how = all, needs all values to NaN, other option is "any"
re_indexed.dropna(axis=1, how="all")

        North    East   South
Years
2017   3000.0  1200.0  2000.0
2018   2500.0  3400.0  1500.0
2019   4000.0     NaN  4000.0
2020      NaN     NaN     NaN
2021      NaN     NaN     NaN

In [51]:
# You can also set a threshold for dropping rows/columns
re_indexed.dropna(thresh=2)

        North    East   South  New
Years
2017   3000.0  1200.0  2000.0  NaN
2018   2500.0  3400.0  1500.0  NaN
2019   4000.0     NaN  4000.0  NaN

In [52]:
re_indexed.dropna(thresh=3)

        North    East   South  New
Years
2017   3000.0  1200.0  2000.0  NaN
2018   2500.0  3400.0  1500.0  NaN

In [53]:
# Dropping based on index
re_indexed.drop("2019")

        North    East   South  New
Years
2017   3000.0  1200.0  2000.0  NaN
2018   2500.0  3400.0  1500.0  NaN
2020      NaN     NaN     NaN  NaN
2021      NaN     NaN     NaN  NaN

In [54]:
# We can easily check for and remove duplicated rows
# We need to create a DataFrame with duplicates first to demonstrate this
df_dup = pd.DataFrame([['A',1],['B',2],['A',1]])
df_dup

   0  1
0  A  1
1  B  2
2  A  1

In [56]:
# Find duplicate rows
df_dup.duplicated()

0    False
1    False
2     True
dtype: bool

In [57]:
# drop duplicate rows
# inplace = True, will make changes to the df permanent
df_dup.drop_duplicates(inplace=True)

In [58]:
df_dup.duplicated()

0    False
1    False
dtype: bool

In [59]:
df_dup

   0  1
0  A  1
1  B  2

### Selecting Entries

In [60]:
# Let's go back to using new_df
new_df

         East    West   North   South
Years
2017   1200.0  1300.0  3000.0  2000.0
2018   3400.0  2400.0  2500.0  1500.0
2019      NaN  3500.0  4000.0  4000.0
2020      NaN     NaN     NaN     NaN
2021      NaN     NaN     NaN     NaN

In [61]:
# Select column name
new_df["North"]

Years
2017    3000.0
2018    2500.0
2019    4000.0
2020       NaN
2021       NaN
Name: North, dtype: float64

In [62]:
# iloc
new_df.iloc[2]

East        NaN
West     3500.0
North    4000.0
South    4000.0
Name: 2019, dtype: float64

In [63]:
# We can use iloc to retrun specific values
new_df.iloc[0, 1]

np.float64(1300.0)

In [64]:
# Slicing with iloc
new_df.iloc[1:3]

         East    West   North   South
Years
2018   3400.0  2400.0  2500.0  1500.0
2019      NaN  3500.0  4000.0  4000.0

In [67]:
# loc
# Let's us access a group of rows and columns based on labels or boolean array
new_df.loc["2019"]

East        NaN
West     3500.0
North    4000.0
South    4000.0
Name: 2019, dtype: float64

In [66]:
new_df.loc[["2018", "2019"]]

         East    West   North   South
Years
2018   3400.0  2400.0  2500.0  1500.0
2019      NaN  3500.0  4000.0  4000.0

In [68]:
# Using boolean arrays with loc
# For each row, we specify True or False depending on if we want that row returned
new_df.loc[[False,False,True,True,True]]

       East    West   North   South
Years
2019    NaN  3500.0  4000.0  4000.0
2020    NaN     NaN     NaN     NaN
2021    NaN     NaN     NaN     NaN

In [70]:
# We can use filtering to return specific sets of information/data
# In the below example, we only want rows where the value for "West" was over 2000
new_df[new_df["West"] > 2000]

         East    West   North   South
Years
2018   3400.0  2400.0  2500.0  1500.0
2019      NaN  3500.0  4000.0  4000.0

### Data alignment

We can add Series and columns in DataFrames together. Since Series are made up of singular columns, it is easy to add them togehter, with DataFrames there is an additional step of specifying the column to add. These examples will add DataFrame columns (Note that for Series, this will work the same, without having to input the column names).

In [71]:
# Adding two columns in a df
new_df["East"] + new_df["North"]

Years
2017    4200.0
2018    5900.0
2019       NaN
2020       NaN
2021       NaN
dtype: float64

In [72]:
# we can use .add to specify the value to be used in case of a NaN value
new_df["East"].add(new_df["North"], fill_value=0)

Years
2017    4200.0
2018    5900.0
2019    4000.0
2020       NaN
2021       NaN
dtype: float64

### Sorting and Ranking

In [74]:
# Sorting by index
# 0 = ascending, 1 = descending
new_df.sort_index(ascending=1)

         East    West   North   South
Years
2017   1200.0  1300.0  3000.0  2000.0
2018   3400.0  2400.0  2500.0  1500.0
2019      NaN  3500.0  4000.0  4000.0
2020      NaN     NaN     NaN     NaN
2021      NaN     NaN     NaN     NaN

In [75]:
# Sort by column, default is asc
new_df.sort_values(by=("North"))

         East    West   North   South
Years
2018   3400.0  2400.0  2500.0  1500.0
2017   1200.0  1300.0  3000.0  2000.0
2019      NaN  3500.0  4000.0  4000.0
2020      NaN     NaN     NaN     NaN
2021      NaN     NaN     NaN     NaN

In [76]:
# Ranking columns
new_df["North"].rank(ascending=0)

Years
2017    2.0
2018    3.0
2019    1.0
2020    NaN
2021    NaN
Name: North, dtype: float64

In [78]:
# Ranking columns, we can add this to the df as a seperate column if we want to
new_df["Rank North"] = new_df["North"].rank(ascending=0)
new_df

         East    West   North   South  Rank North
Years
2017   1200.0  1300.0  3000.0  2000.0         2.0
2018   3400.0  2400.0  2500.0  1500.0         3.0
2019      NaN  3500.0  4000.0  4000.0         1.0
2020      NaN     NaN     NaN     NaN         NaN
2021      NaN     NaN     NaN     NaN         NaN

### Summary Statistics

In [79]:
# Describe
# Very useful, gives summary statistics for the whole df
new_df.describe()

              East    West        North        South  Rank North
count     2.000000     3.0     3.000000     3.000000         3.0
mean   2300.000000  2400.0  3166.666667  2500.000000         2.0
std    1555.634919  1100.0   763.762616  1322.875656         1.0
min    1200.000000  1300.0  2500.000000  1500.000000         1.0
25%    1750.000000  1850.0  2750.000000  1750.000000         1.5
50%    2300.000000  2400.0  3000.000000  2000.000000         2.0
75%    2850.000000  2950.0  3500.000000  3000.000000         2.5
max    3400.000000  3500.0  4000.000000  4000.000000         3.0

In [80]:
# sum
new_df.sum()

East          4600.0
West          7200.0
North         9500.0
South         7500.0
Rank North       6.0
dtype: float64

In [81]:
# Cumulative sum
new_df.cumsum()

         East    West   North   South  Rank North
Years
2017   1200.0  1300.0  3000.0  2000.0         2.0
2018   4600.0  3700.0  5500.0  3500.0         5.0
2019      NaN  7200.0  9500.0  7500.0         6.0
2020      NaN     NaN     NaN     NaN         NaN
2021      NaN     NaN     NaN     NaN         NaN

In [82]:
# min values in each column
new_df.min()

East          1200.0
West          1300.0
North         2500.0
South         1500.0
Rank North       1.0
dtype: float64

In [83]:
# max value in each column
new_df.max()

East          3400.0
West          3500.0
North         4000.0
South         4000.0
Rank North       3.0
dtype: float64

### Index Heirarchy

In [84]:
# Creating a DataFrame with a hierarchical index
# We are using numpy arange to create a range of numbers, and re-shaping it so that the numbers will fit on a 4x4 grid
df_temp = pd.DataFrame(np.arange(16).reshape(4,4), index = [['2018','2018','2019','2019'],['Jan','Feb','Jan','Feb']],
                   columns = [['NY','NY','LA','LA'],['Cold','Hot','Cold','Hot']])
df_temp

           NY       LA
         Cold Hot Cold Hot
2018 Jan    0   1    2   3
     Feb    4   5    6   7
2019 Jan    8   9   10  11
     Feb   12  13   14  15

In [87]:
# We can add index and column names
df_temp.index.names=["Year", "Month"]
df_temp.columns.names=["State","Temp"]
df_temp

State        NY       LA
Temp       Cold Hot Cold Hot
Year Month
2018 Jan      0   1    2   3
     Feb      4   5    6   7
2019 Jan      8   9   10  11
     Feb     12  13   14  15

In [88]:
# Swap levels of a particular axis
#axis=0 --> index axis=1 --> columns
df_temp.swaplevel("State","Temp", axis=1)

Temp       Cold Hot Cold Hot
State        NY  NY   LA  LA
Year Month
2018 Jan      0   1    2   3
     Feb      4   5    6   7
2019 Jan      8   9   10  11
     Feb     12  13   14  15

In [89]:
# Sorting on the first level of the index
df_temp.sort_index(level=0)

State        NY       LA
Temp       Cold Hot Cold Hot
Year Month
2018 Feb      4   5    6   7
     Jan      0   1    2   3
2019 Feb     12  13   14  15
     Jan      8   9   10  11

In [90]:
# Sorting on the second level of the index
df_temp.sort_index(level=1)

State        NY       LA
Temp       Cold Hot Cold Hot
Year Month
2018 Feb      4   5    6   7
2019 Feb     12  13   14  15
2018 Jan      0   1    2   3
2019 Jan      8   9   10  11

In [91]:
# Accessing singular columns in a multi-index df
df_temp["NY"]["Cold"]

Year  Month
2018  Jan       0
      Feb       4
2019  Jan       8
      Feb      12
Name: Cold, dtype: int64

In [92]:
# You can also use iloc
df_temp.iloc[0]

State  Temp
NY     Cold    0
       Hot     1
LA     Cold    2
       Hot     3
Name: (2018, Jan), dtype: int64

In [94]:
# using loc for the same thing, Jan 2018
df_temp.loc["2018", "Jan"]

State  Temp
NY     Cold    0
       Hot     1
LA     Cold    2
       Hot     3
Name: (2018, Jan), dtype: int64