In [1]:
import numpy as np
import pandas as pd

### CSV files in Pandas

Download the iris dataset through the terminal. Make sure it is in the same fodler as this notebook

curl -L bit.ly/sparta_iris > iris.csv

In [3]:
# using read_csv
iris = pd.read_csv("iris.csv")
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
# get the first 5 rows of df
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
# Write a df to a new csv
iris.to_csv("new_iris_file.csv") # I can add index=False if I don't want to keep the left side numbers

In [11]:
# Use .groupby, what does it do?
iris.groupby("species").mean() # this groups the data by species, then calculates the mean of each numeric column

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.418         1.464        0.244
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [16]:
# Iterate through the data (using a for loop)
for index, row in iris.head(10).iterrows():
    if row['petal_length'] == 1.4:
        print(index)

# my example is taking the index for the first ten rows where the petal length is 1.4
# iterrows gives both index and row data, so row needs to be specified, as well as
# in the second line I can't just write ['petal_length'] == 1.4 because a string doesn't equal a number
# must have row before it

0
1
4
6
8

In [19]:
# Use .describe() on the data
iris.describe() # gives a bunch of statistics

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

### On the iris dataset

In [21]:
# Add a rank column, ranking petal length in asc order
iris["Rank PL"] = iris["petal_length"].rank(ascending=True)
iris
# so for example, the Rank PL is low for row 2 which has a low petal length of 1.3, the decimals
# of the Rank PL indicates the ties and multiple of the same type of petal length so their rank is grouped

     sepal_length  sepal_width  petal_length  petal_width    species  Rank PL
0             5.1          3.5           1.4          0.2     setosa     17.5
1             4.9          3.0           1.4          0.2     setosa     17.5
2             4.7          3.2           1.3          0.2     setosa      8.0
3             4.6          3.1           1.5          0.2     setosa     30.5
4             5.0          3.6           1.4          0.2     setosa     17.5
..            ...          ...           ...          ...        ...      ...
145           6.7          3.0           5.2          2.3  virginica    117.5
146           6.3          2.5           5.0          1.9  virginica    106.5
147           6.5          3.0           5.2          2.0  virginica    117.5
148           6.2          3.4           5.4          2.3  virginica    121.5
149           5.9          3.0           5.1          1.8  virginica    112.5

[150 rows x 6 columns]

In [22]:
# Find the mean of each column for each species
iris.groupby("species").mean()
# so originally I thought I had already done this through iris.describe(), but no that calculates the
# mean of the whole dataset, whereas this question asks for each species, so I need to group by first
# to split the data into species, then calculate the means

            sepal_length  sepal_width  petal_length  petal_width  Rank PL
species
setosa             5.006        3.418         1.464        0.244    25.50
versicolor         5.936        2.770         4.260        1.326    76.39
virginica          6.588        2.974         5.552        2.026   124.61

In [25]:
# Create a new df for each species separately (3 total)
setosa_df = iris[iris['species'] == 'setosa']
versicolor_df = iris[iris['species'] == 'versicolor']
virginica_df = iris[iris['species'] == 'virginica']
# it seems hard to remember but it's easier than you think: the inside brackets are just checking if the species
# is the one you need from the iris dataset, then the outside ones are just asking to return that one and assign
# it a name for the new dataframe
setosa_df.head(10) # it has 49 rows so I'm using head to only show 10

   sepal_length  sepal_width  petal_length  petal_width species  Rank PL
0           5.1          3.5           1.4          0.2  setosa     17.5
1           4.9          3.0           1.4          0.2  setosa     17.5
2           4.7          3.2           1.3          0.2  setosa      8.0
3           4.6          3.1           1.5          0.2  setosa     30.5
4           5.0          3.6           1.4          0.2  setosa     17.5
5           5.4          3.9           1.7          0.4  setosa     46.5
6           4.6          3.4           1.4          0.3  setosa     17.5
7           5.0          3.4           1.5          0.2  setosa     30.5
8           4.4          2.9           1.4          0.2  setosa     17.5
9           4.9          3.1           1.5          0.1  setosa     30.5

In [26]:
# Create 2 final df, one for sepal info and one for petal info (with data from all three species in each)
sepal_df = iris[['sepal_length', 'sepal_width', 'species']]
petal_df = iris[['petal_length', 'petal_width', 'species']]
# okay so the reason it is not in single brackets is because otherwise it would be looking for one column named
# those three parameters, and won't find it, the second set of square brackets shows that it is a list of columns
petal_df.head(5)

   petal_length  petal_width species
0           1.4          0.2  setosa
1           1.4          0.2  setosa
2           1.3          0.2  setosa
3           1.5          0.2  setosa
4           1.4          0.2  setosa

### JSON files and Pandas

In [27]:
# first on Pycharm I did pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

In [32]:
file_path = "iris.json"
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "rtatman/iris-dataset-json-version",
  file_path
)

print("First 5 records:", df.head())

C:\Users\hites\AppData\Local\Temp\ipykernel_20616\1555013186.py:2: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Downloading to C:\Users\hites\.cache\kagglehub\datasets\rtatman\iris-dataset-json-version\versions\1\iris.json...

100%|██████████| 15.4k/15.4k [00:00<00:00, 10.8MB/s]

First 5 records:    sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

In [33]:
# on the kaggle website, press code and the instructions are there, all I had to change was
# adding the iris.json as the file path just to name it, and just closing the bracket on file_path

### Merging

In [36]:
# Find a way to merge your sepal_info and petal_info dataframes
merged_df = pd.concat([sepal_df, petal_df], axis=1) # the reason for axis=1 is so that pandas merges them
# column wise, rather than it defaulting to axis=0 and now petal_df would be underneath sepal_df vertically
merged_df.head()

   sepal_length  sepal_width species  petal_length  petal_width species
0           5.1          3.5  setosa           1.4          0.2  setosa
1           4.9          3.0  setosa           1.4          0.2  setosa
2           4.7          3.2  setosa           1.3          0.2  setosa
3           4.6          3.1  setosa           1.5          0.2  setosa
4           5.0          3.6  setosa           1.4          0.2  setosa

In [37]:
# Drop repeated columns from your merged df
# but as you can see above this creates two columns of the same stuff
merged_df = merged_df.loc[:, ~merged_df.columns.duplicated()]
# okay this one is hella confusing, basically you are using loc to select the columns, the : means keep all rows,
# the ~ means NOT, so basically without it you would mark all unique columns as false which would delete them and
# only leave the duplicate, so you need it, and the rest is just using the duplicated method
# also remember you aren't deleting the old duplicate column, only selecting the ones you want to keep
merged_df.head()

   sepal_length  sepal_width species  petal_length  petal_width
0           5.1          3.5  setosa           1.4          0.2
1           4.9          3.0  setosa           1.4          0.2
2           4.7          3.2  setosa           1.3          0.2
3           4.6          3.1  setosa           1.5          0.2
4           5.0          3.6  setosa           1.4          0.2

### Concatenation

In [41]:
# Use .concat() on your main df. What does it do?
pd.concat([iris, iris])

     sepal_length  sepal_width  petal_length  petal_width    species  Rank PL
0             5.1          3.5           1.4          0.2     setosa     17.5
1             4.9          3.0           1.4          0.2     setosa     17.5
2             4.7          3.2           1.3          0.2     setosa      8.0
3             4.6          3.1           1.5          0.2     setosa     30.5
4             5.0          3.6           1.4          0.2     setosa     17.5
..            ...          ...           ...          ...        ...      ...
145           6.7          3.0           5.2          2.3  virginica    117.5
146           6.3          2.5           5.0          1.9  virginica    106.5
147           6.5          3.0           5.2          2.0  virginica    117.5
148           6.2          3.4           5.4          2.3  virginica    121.5
149           5.9          3.0           5.1          1.8  virginica    112.5

[300 rows x 6 columns]

In [ ]:
# it looks the same but in reality instead of merging data like an inner join in sql, it just pastes them
# together, so here I concatenated iris with itself and it just pasted the same table again below it,
# 300 rows instead of 150, also if I wanted them side by side I could specify axis=1 as the default is axis=0